In [1399]:
import pandas as pd
import numpy as np
import warnings 
warnings.simplefilter("ignore")

In [1400]:
#importando bases de datos y convirtiendo a dataframe

sharkdf=pd.read_csv('attacks.csv', sep=',', encoding='latin-1')

sharkdf.shape

(25723, 24)

In [1401]:
#Inspeccionando base de datos
sharkdf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25723 entries, 0 to 25722
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Case Number             8702 non-null   object
 1   Date                    6302 non-null   object
 2   Year                    6300 non-null   float64
 3   Type                    6298 non-null   object
 4   Country                 6252 non-null   object
 5   Area                    5847 non-null   object
 6   Location                5762 non-null   object
 7   Activity                5758 non-null   object
 8   Name                    6092 non-null   object
 9   Sex                     5737 non-null   object
 10  Age                     3471 non-null   object
 11  Injury                  6274 non-null   object
 12  Fatal (Y/N)             5763 non-null   object
 13  Time                    2948 non-null   object
 14  Species                 3464 non-null   object
 15  Investigator or Source  6285 non-null   object
 16  pdf                     6302 non-null   object
 17  href formula            6301 non-null   object
 18  href                    6302 non-null   object
 19  Case Number.1           6302 non-null   object
 20  Case Number.2           6302 non-null   object
 21  original order          6309 non-null   float64
 22  Unnamed: 22             1 non-null      object
 23  Unnamed: 23             2 non-null      object
dtypes: float64(2), object(22)
memory usage: 4.7+ MB

In [1402]:
sharkdf

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,...,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,AdysonÂ McNeely,F,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,...,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0,NaN,NaN
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,...,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25718,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25719,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25720,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25721,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25722,xx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [1403]:
sharkdf.columns

Index(['Case Number', 'Date', 'Year', 'Type', 'Country', 'Area', 'Location',
       'Activity', 'Name', 'Sex ', 'Age', 'Injury', 'Fatal (Y/N)', 'Time',
       'Species ', 'Investigator or Source', 'pdf', 'href formula', 'href',
       'Case Number.1', 'Case Number.2', 'original order', 'Unnamed: 22',
       'Unnamed: 23'],
      dtype='object')

In [1404]:
sharkdf = sharkdf.rename(columns={'Species ': 'Species', 'Sex ': 'Sex', 'Fatal (Y/N)' : 'Fatal',
                                  'Investigator or Source': 'InvestigatorSource', 'href formula': 'hrefformula',
                                  'Case Number.1': 'CaseNumber.1', 'Case Number.2': 'CaseNumber.2', 
                                 'original order': 'originalorder', 'Unnamed: 22': 'Unnamed22', 'Unnamed: 23': 'Unnamed23', 'Case Number': 'CaseNumber'})
sharkdf.columns

Index(['CaseNumber', 'Date', 'Year', 'Type', 'Country', 'Area', 'Location',
       'Activity', 'Name', 'Sex', 'Age', 'Injury', 'Fatal', 'Time', 'Species',
       'InvestigatorSource', 'pdf', 'hrefformula', 'href', 'CaseNumber.1',
       'CaseNumber.2', 'originalorder', 'Unnamed22', 'Unnamed23'],
      dtype='object')

In [1405]:
sharkdf.isnull().sum()

CaseNumber            17021
Date                  19421
Year                  19423
Type                  19425
Country               19471
Area                  19876
Location              19961
Activity              19965
Name                  19631
Sex                   19986
Age                   22252
Injury                19449
Fatal                 19960
Time                  22775
Species               22259
InvestigatorSource    19438
pdf                   19421
hrefformula           19422
href                  19421
CaseNumber.1          19421
CaseNumber.2          19421
originalorder         19414
Unnamed22             25722
Unnamed23             25721
dtype: int64

In [1406]:
sharkdf.T.shape

(24, 25723)

In [1407]:
#Cuando transponemos la tabla, si la columna tiene mÃ¡s de la mitad de NaN no lo consideraremos.
MaxNa = 15
sharkdf=sharkdf.T.loc[:, (sharkdf.T.isnull().sum(axis=0) <= MaxNa)]

In [1408]:
sharkdf=sharkdf.T

In [1409]:
sharkdf.isnull().sum()

CaseNumber               1
Date                     0
Year                     2
Type                     4
Country                 50
Area                   455
Location               540
Activity               544
Name                   210
Sex                    565
Age                   2831
Injury                  28
Fatal                  539
Time                  3354
Species               2838
InvestigatorSource      17
pdf                      0
hrefformula              1
href                     0
CaseNumber.1             0
CaseNumber.2             0
originalorder            0
Unnamed22             6301
Unnamed23             6300
dtype: int64

In [1410]:
sharkdf.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6302 entries, 0 to 6301
Data columns (total 24 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   CaseNumber          6301 non-null   object
 1   Date                6302 non-null   object
 2   Year                6300 non-null   object
 3   Type                6298 non-null   object
 4   Country             6252 non-null   object
 5   Area                5847 non-null   object
 6   Location            5762 non-null   object
 7   Activity            5758 non-null   object
 8   Name                6092 non-null   object
 9   Sex                 5737 non-null   object
 10  Age                 3471 non-null   object
 11  Injury              6274 non-null   object
 12  Fatal               5763 non-null   object
 13  Time                2948 non-null   object
 14  Species             3464 non-null   object
 15  InvestigatorSource  6285 non-null   object
 16  pdf                 6302 non-null   object
 17  hrefformula         6301 non-null   object
 18  href                6302 non-null   object
 19  CaseNumber.1        6302 non-null   object
 20  CaseNumber.2        6302 non-null   object
 21  originalorder       6302 non-null   object
 22  Unnamed22           1 non-null      object
 23  Unnamed23           2 non-null      object
dtypes: object(24)
memory usage: 1.2+ MB

In [1411]:
#Comenzamos limpiando los aÃ±os
#Solo consideramos de 1900 a 2018

sharkdf.Year.unique()

array([2018.0, 2017.0, nan, 2016.0, 2015.0, 2014.0, 2013.0, 2012.0,
       2011.0, 2010.0, 2009.0, 2008.0, 2007.0, 2006.0, 2005.0, 2004.0,
       2003.0, 2002.0, 2001.0, 2000.0, 1999.0, 1998.0, 1997.0, 1996.0,
       1995.0, 1984.0, 1994.0, 1993.0, 1992.0, 1991.0, 1990.0, 1989.0,
       1969.0, 1988.0, 1987.0, 1986.0, 1985.0, 1983.0, 1982.0, 1981.0,
       1980.0, 1979.0, 1978.0, 1977.0, 1976.0, 1975.0, 1974.0, 1973.0,
       1972.0, 1971.0, 1970.0, 1968.0, 1967.0, 1966.0, 1965.0, 1964.0,
       1963.0, 1962.0, 1961.0, 1960.0, 1959.0, 1958.0, 1957.0, 1956.0,
       1955.0, 1954.0, 1953.0, 1952.0, 1951.0, 1950.0, 1949.0, 1948.0,
       1848.0, 1947.0, 1946.0, 1945.0, 1944.0, 1943.0, 1942.0, 1941.0,
       1940.0, 1939.0, 1938.0, 1937.0, 1936.0, 1935.0, 1934.0, 1933.0,
       1932.0, 1931.0, 1930.0, 1929.0, 1928.0, 1927.0, 1926.0, 1925.0,
       1924.0, 1923.0, 1922.0, 1921.0, 1920.0, 1919.0, 1918.0, 1917.0,
       1916.0, 1915.0, 1914.0, 1913.0, 1912.0, 1911.0, 1910.0, 1909.0,
       1908.0, 1907.0, 1906.0, 1905.0, 1904.0, 1903.0, 1902.0, 1901.0,
       1900.0, 1899.0, 1898.0, 1897.0, 1896.0, 1895.0, 1894.0, 1893.0,
       1892.0, 1891.0, 1890.0, 1889.0, 1888.0, 1887.0, 1886.0, 1885.0,
       1884.0, 1883.0, 1882.0, 1881.0, 1880.0, 1879.0, 1878.0, 1877.0,
       1876.0, 1875.0, 1874.0, 1873.0, 1872.0, 1871.0, 1870.0, 1869.0,
       1868.0, 1867.0, 1866.0, 1865.0, 1864.0, 1863.0, 1862.0, 1861.0,
       1860.0, 1859.0, 1858.0, 1857.0, 1856.0, 1855.0, 1853.0, 1852.0,
       1851.0, 1850.0, 1849.0, 1847.0, 1846.0, 1845.0, 1844.0, 1842.0,
       1841.0, 1840.0, 1839.0, 1837.0, 1836.0, 1835.0, 1834.0, 1832.0,
       1831.0, 1830.0, 1829.0, 1828.0, 1827.0, 1826.0, 1825.0, 1823.0,
       1822.0, 1819.0, 1818.0, 1817.0, 1816.0, 1815.0, 1812.0, 1811.0,
       1810.0, 1808.0, 1807.0, 1805.0, 1804.0, 1803.0, 1802.0, 1801.0,
       1800.0, 1797.0, 1792.0, 1791.0, 1788.0, 1787.0, 1786.0, 1785.0,
       1784.0, 1783.0, 1780.0, 1779.0, 1776.0, 1771.0, 1767.0, 1764.0,
       1758.0, 1753.0, 1751.0, 1749.0, 1755.0, 1748.0, 1742.0, 1738.0,
       1733.0, 1723.0, 1721.0, 1703.0, 1700.0, 1642.0, 1638.0, 1637.0,
       1617.0, 1595.0, 1580.0, 1555.0, 1554.0, 1543.0, 500.0, 77.0, 5.0,
       0.0], dtype=object)

In [1412]:
sharkdf.Year.isnull().sum()

2

In [1413]:
sharkdf.Year = sharkdf.Year.astype(float)

In [1414]:
sharkdf = sharkdf[sharkdf['Year'] >= 1900]

In [1415]:
sharkdf.Year=sharkdf.Year.dropna()

In [1416]:
sharkdf.Year.isnull().sum()

0

In [1417]:
sharkdf.Year.unique()

array([2018., 2017., 2016., 2015., 2014., 2013., 2012., 2011., 2010.,
       2009., 2008., 2007., 2006., 2005., 2004., 2003., 2002., 2001.,
       2000., 1999., 1998., 1997., 1996., 1995., 1984., 1994., 1993.,
       1992., 1991., 1990., 1989., 1969., 1988., 1987., 1986., 1985.,
       1983., 1982., 1981., 1980., 1979., 1978., 1977., 1976., 1975.,
       1974., 1973., 1972., 1971., 1970., 1968., 1967., 1966., 1965.,
       1964., 1963., 1962., 1961., 1960., 1959., 1958., 1957., 1956.,
       1955., 1954., 1953., 1952., 1951., 1950., 1949., 1948., 1947.,
       1946., 1945., 1944., 1943., 1942., 1941., 1940., 1939., 1938.,
       1937., 1936., 1935., 1934., 1933., 1932., 1931., 1930., 1929.,
       1928., 1927., 1926., 1925., 1924., 1923., 1922., 1921., 1920.,
       1919., 1918., 1917., 1916., 1915., 1914., 1913., 1912., 1911.,
       1910., 1909., 1908., 1907., 1906., 1905., 1904., 1903., 1902.,
       1901., 1900.])

In [1418]:
sharkdf.shape

(5562, 24)

In [1419]:
sharkdf.dropna(subset=['Type'], inplace=True)
sharkdf.dropna(subset=['CaseNumber'], inplace=True)
sharkdf.dropna(subset=['hrefformula'], inplace=True)

In [1420]:
sharkdf.dropna(subset=['Species'], inplace=True)
sharkdf.dropna(subset=['Location'], inplace=True)

In [1421]:
sharkdf.shape

(3138, 24)

In [1422]:
sharkdf.isnull().sum()

CaseNumber               0
Date                     0
Year                     0
Type                     0
Country                  3
Area                    79
Location                 0
Activity               172
Name                    75
Sex                    275
Age                   1018
Injury                   7
Fatal                  409
Time                  1286
Species                  0
InvestigatorSource       7
pdf                      0
hrefformula              0
href                     0
CaseNumber.1             0
CaseNumber.2             0
originalorder            0
Unnamed22             3138
Unnamed23             3138
dtype: int64

In [1423]:
#Limpiando el tiempo
sharkdf.Time.head(50)

0              18h00
3                NaN
4                NaN
6     Late afternoon
7                NaN
8              17h00
10           Morning
13             08h15
14               NaN
16             10h30
18             10h40
20             07h00
21             09h30
22         Afternoon
23             21h50
24             09h40
25               NaN
26               NaN
30             09h30
31               NaN
32             17h00
33             18h00
34             15h00
35             09h30
36             17h35
37             15h30
38             07h30
39               NaN
40       19h00, Dusk
42             16h00
43             18h00
44               NaN
45               NaN
46               NaN
47             08h00
48             15h30
49             15h01
50               NaN
51    Late afternoon
52               NaN
53             18h00
55               NaN
57               NaN
58               NaN
59               NaN
60             13h45
63             16h00
64             23h30
65               NaN
66             09h00
Name: Time, dtype: object

In [1424]:
#Importamos regex y filtramos
import re
sharkdf.Time=sharkdf.Time.astype(str).apply(lambda x : re.sub('[a-zA-Z]','', x))
sharkdf.Time=sharkdf.Time.apply(lambda x : re.sub('-\d\d\d\d','', x))
sharkdf.Time=sharkdf.Time.apply(lambda x : re.sub('\d\d\d\d/\d\d\d\d','0', x))
sharkdf.Time=sharkdf.Time.apply(lambda x : re.sub('\d\d\d\d / \d\d\d\d','0', x))
sharkdf.Time=sharkdf.Time.apply(lambda x : re.sub('>\d\d\d\d','0', x))
sharkdf.Time=sharkdf.Time.apply(lambda x : re.sub('\d\d\d\d & \d\d\d\d','0', x))
sharkdf.Time=sharkdf.Time.apply(lambda x : re.sub('\xa0 ','0', x))
sharkdf.Time=sharkdf.Time.apply(lambda x : re.sub('"  1100"','1100', x))
sharkdf.Time=sharkdf.Time.apply(lambda x : re.sub('  1200','1200', x))
sharkdf.Time=sharkdf.Time.apply(lambda x : re.sub('0900 - 0930','0', x))
sharkdf.Time=sharkdf.Time.apply(lambda x : re.sub('    2000.08.21','0', x))
sharkdf.Time=sharkdf.Time.apply(lambda x : re.sub('1400 - 1500','0', x))
sharkdf.Time=sharkdf.Time.apply(lambda x : re.sub('8:04','2000', x))
sharkdf.Time=sharkdf.Time.apply(lambda x : re.sub('180','1800', x))
sharkdf.Time=sharkdf.Time.apply(lambda x : re.sub('2045()','0', x))
sharkdf.Time=sharkdf.Time.apply(lambda x : re.sub('170','1700', x))
sharkdf.Time=sharkdf.Time.apply(lambda x : re.sub('103001330','0', x))
sharkdf.Time=sharkdf.Time.apply(lambda x : re.sub('100001400','0', x))
sharkdf.Time=sharkdf.Time.apply(lambda x : re.sub('150001545','0', x))
sharkdf.Time=sharkdf.Time.apply(lambda x : re.sub('1000  1400','0', x))
sharkdf.Time=sharkdf.Time.apply(lambda x : re.sub('1030  1330','0', x))
sharkdf.Time=sharkdf.Time.apply(lambda x : re.sub('0 ()','0', x))
sharkdf.Time=sharkdf.Time.apply(lambda x : re.sub('-','0', x))
sharkdf.Time=sharkdf.Time.apply(lambda x : re.sub('2   ','0', x))
sharkdf.Time=sharkdf.Time.apply(lambda x : re.sub(' 05000800','0', x))
sharkdf.Time=sharkdf.Time.apply(lambda x : re.sub('17001740','0', x))
sharkdf.Time=sharkdf.Time.apply(lambda x : re.sub('16301800','0', x))
sharkdf.Time=sharkdf.Time.apply(lambda x : re.sub('1830?','0', x))
sharkdf.Time=sharkdf.Time.apply(lambda x : re.sub('00','0', x))
sharkdf.Time=sharkdf.Time.apply(lambda x : re.sub(' 140','1400', x))

In [1425]:
sharkdf.Time = pd.to_numeric(sharkdf['Time'], errors='coerce')

In [1426]:
sharkdf = sharkdf[sharkdf['Time'] >= 0]

In [1427]:
sharkdf.Time.unique()

array([1.8000e+03, 1.7000e+03, 8.1500e+02, 1.0300e+03, 1.0400e+03,
       7.0000e+01, 9.3000e+02, 2.1500e+03, 9.4000e+02, 1.5000e+02,
       1.7350e+03, 1.5300e+03, 7.3000e+02, 1.6000e+02, 8.0000e+01,
       1.5010e+03, 1.3450e+03, 2.3300e+03, 9.0000e+01, 1.4300e+03,
       0.0000e+00, 1.2300e+03, 1.4000e+02, 1.8450e+03, 6.0000e+01,
       1.0000e+02, 1.3300e+03, 1.0450e+03, 1.1200e+03, 7.4500e+02,
       1.1000e+02, 1.9300e+03, 8.3000e+02, 1.5450e+03, 1.2000e+02,
       8.5000e+02, 2.0000e+01, 1.5150e+03, 1.6300e+03, 1.1300e+03,
       2.2000e+02, 1.6200e+03, 1.5250e+03, 1.7300e+03, 1.3200e+03,
       1.0150e+03, 1.8150e+03, 1.3500e+03, 1.9200e+03, 1.0250e+03,
       1.6450e+03, 1.5520e+03, 6.1500e+02, 1.4400e+03, 1.9450e+03,
       1.9000e+02, 1.0100e+03, 8.4500e+02, 1.2100e+03, 1.8050e+03,
       1.2250e+03, 1.7510e+03, 1.6120e+03, 1.2450e+03, 1.0500e+03,
       1.4150e+03, 1.3000e+02, 9.4500e+02, 1.1450e+03, 6.4500e+02,
       5.0000e+01, 3.3000e+02, 1.1150e+03, 6.3000e+02, 2.0000e+02,
       1.6400e+03, 1.6180e+03, 1.1100e+03, 1.7500e+03, 8.2000e+02,
       2.0300e+03, 1.5190e+03, 1.0550e+03, 1.5550e+03, 2.3000e+02,
       1.2400e+03, 1.6050e+03, 1.4100e+03, 1.2500e+03, 1.3400e+03,
       1.3240e+03, 1.4500e+03, 1.1400e+03, 8.1000e+02, 1.5560e+03,
       9.0500e+02, 7.1500e+02, 1.4200e+03, 7.2000e+02, 1.9280e+03,
       1.2380e+03, 5.5000e+02, 1.5500e+03, 1.1050e+03, 1.5400e+03,
       5.4500e+02, 1.3250e+03, 9.5000e+02, 1.3260e+03, 9.1100e+02,
       1.3150e+03, 1.7450e+03, 1.8200e+03, 1.5350e+03, 1.4550e+03,
       8.0500e+02, 1.9150e+03, 1.0350e+03, 1.4450e+03, 2.1000e+02,
       9.3500e+02, 1.0270e+03, 1.0160e+03, 9.2000e+02, 1.7200e+03,
       1.3550e+03, 1.8500e+03, 1.1115e+04, 1.2390e+03, 7.0500e+02,
       1.2150e+03, 1.1500e+03, 1.7150e+03, 1.2050e+03, 1.5200e+03,
       1.6100e+03, 6.1000e+02, 1.6150e+03, 7.0800e+02, 1.2200e+03,
       1.2550e+03, 1.6140e+03, 1.7110e+03, 3.0000e+01, 1.0700e+02,
       1.3530e+03, 1.3230e+03, 8.4000e+02, 1.1560e+03, 1.4350e+03,
       1.3345e+04, 1.2340e+03, 1.1530e+03, 1.2350e+03, 1.7400e+03,
       1.1250e+03, 1.8250e+03, 1.0280e+03, 9.1500e+02, 2.0150e+03,
       1.4160e+03, 9.5500e+02, 1.5050e+03, 7.1900e+02, 1.1060e+03,
       1.1580e+03, 1.1510e+03, 1.8120e+03, 7.1000e+02, 7.4000e+02,
       1.2330e+03, 1.5060e+03, 1.2540e+03, 1.6350e+03, 1.6550e+03,
       1.6500e+03, 5.4000e+02, 2.1300e+03, 8.5700e+02, 8.3500e+02,
       4.0000e+01, 1.0200e+03, 1.8100e+03, 1.4000e+03, 1.2480e+03,
       6.5000e+02, 1.8400e+03, 1.0000e+01, 7.3200e+02, 1.3100e+03,
       1.9350e+03, 1.3200e+02, 1.7100e+03, 1.6230e+03, 1.3050e+03])

In [1428]:
sharkdf['Age']=sharkdf['Age'].fillna('Unknown')

In [1429]:
sharkdf.Age.unique()

array(['57', '15', '21', 'Unknown', '30', '60', '32', '33', '12', '19',
       '25', '10', '69', '18', '35', '40s', '54', '22', '31', '40', '37',
       '13', '34', '50', '46', '48', '17', '28', '55', '20', '65', '73',
       '58', '36', '60s', '51', '61', '59', '42', '6', '27', '29', '23',
       '24', '43', '9', '44', '14', '62', '52', '38', '68', '16', '11',
       '47', '63', '26', '71', '41', '53', '20s', '39', '66', '45', '74',
       '64', '8', '56', '49', '7', '70', '18 or 20', '30s', '77',
       '36 & 26', '8 or 10', ' ', '30 or 36', '6Â½', '5', ' 28', '20?',
       '67', '>50', '9 & 12', '21, 34,24 & 35', '13 or 18', '7 or 8'],
      dtype=object)

In [1430]:
sharkdf.Age=sharkdf.Age.apply(lambda x : re.sub('[a-zA-Z]','', x))
sharkdf.Age=sharkdf.Age.apply(lambda x : re.sub('>\d\d','', x))
sharkdf.Age=sharkdf.Age.apply(lambda x : re.sub('\d  \d','', x))
sharkdf.Age=sharkdf.Age.apply(lambda x : re.sub('""','', x))
sharkdf.Age=sharkdf.Age.apply(lambda x : re.sub('\d\d & \d\d', '', x))
sharkdf.Age=sharkdf.Age.apply(lambda x : re.sub('\d & \d\d', '', x))
sharkdf.Age=sharkdf.Age.apply(lambda x : re.sub( "60'", '60', x))
sharkdf.Age=sharkdf.Age.apply(lambda x : re.sub('-20', '', x))
sharkdf.Age=sharkdf.Age.apply(lambda x : re.sub('\xa0', '', x))
sharkdf.Age=sharkdf.Age.apply(lambda x : re.sub('20?', '', x))
sharkdf.Age=sharkdf.Age.apply(lambda x : re.sub(' 30', '', x))
sharkdf.Age=sharkdf.Age.apply(lambda x : re.sub(' 8', '', x))
sharkdf.Age=sharkdf.Age.apply(lambda x : re.sub('0', '', x))
sharkdf.Age=sharkdf.Age.apply(lambda x : re.sub(' 43', '43', x))
sharkdf.Age=sharkdf.Age.apply(lambda x : re.sub(' 11', '11', x))
sharkdf.Age=sharkdf.Age.apply(lambda x : re.sub('. 33', '33', x))
sharkdf.Age=sharkdf.Age.apply(lambda x : re.sub('1, 34,', '33', x))
sharkdf.Age=sharkdf.Age.apply(lambda x : re.sub('37, 67, 35, 7,  ? & 7', '', x))
sharkdf.Age=sharkdf.Age.apply(lambda x : re.sub('6Â½', '', x))
sharkdf.Age=sharkdf.Age.apply(lambda x : re.sub('1 & ', '', x))
sharkdf.Age=sharkdf.Age.apply(lambda x : re.sub(' & 19', '', x)) 
sharkdf.Age=sharkdf.Age.apply(lambda x : re.sub(' & 7', '', x)) 
sharkdf.Age=sharkdf.Age.apply(lambda x : re.sub('37, 67, 35, 7, ', '', x))
sharkdf.Age=sharkdf.Age.apply(lambda x : re.sub('40s', '', x)) 
sharkdf.Age=sharkdf.Age.apply(lambda x : re.sub('60s', '', x))

In [1431]:
sharkdf.shape

(1560, 24)

In [1432]:
list(sharkdf.Age.unique())

['57',
 '15',
 '1',
 '',
 '3',
 '6',
 '33',
 '19',
 '5',
 '69',
 '18',
 '35',
 '4',
 '54',
 '31',
 '37',
 '13',
 '34',
 '46',
 '48',
 '17',
 '8',
 '55',
 '65',
 '73',
 '58',
 '36',
 '51',
 '61',
 '59',
 '7',
 '9',
 '43',
 '44',
 '14',
 '38',
 '68',
 '16',
 '11',
 '47',
 '63',
 '71',
 '41',
 '53',
 '39',
 '66',
 '45',
 '74',
 '64',
 '56',
 '49',
 '77',
 ' ',
 '?',
 '67']

In [1433]:
sharkdf.Age = pd.to_numeric(sharkdf['Age'], errors='coerce')

In [1434]:
list(sharkdf.Age.unique())

[57.0,
 15.0,
 1.0,
 nan,
 3.0,
 6.0,
 33.0,
 19.0,
 5.0,
 69.0,
 18.0,
 35.0,
 4.0,
 54.0,
 31.0,
 37.0,
 13.0,
 34.0,
 46.0,
 48.0,
 17.0,
 8.0,
 55.0,
 65.0,
 73.0,
 58.0,
 36.0,
 51.0,
 61.0,
 59.0,
 7.0,
 9.0,
 43.0,
 44.0,
 14.0,
 38.0,
 68.0,
 16.0,
 11.0,
 47.0,
 63.0,
 71.0,
 41.0,
 53.0,
 39.0,
 66.0,
 45.0,
 74.0,
 64.0,
 56.0,
 49.0,
 77.0,
 67.0]

In [1435]:
sharkdf.Age.isnull().sum()

342

In [1436]:
sharkdf = sharkdf[sharkdf['Age'] >= 0]

In [1437]:
sharkdf.Age.unique()

array([57., 15.,  1.,  3.,  6., 33., 19.,  5., 69., 18., 35.,  4., 54.,
       31., 37., 13., 34., 46., 48., 17.,  8., 55., 65., 73., 58., 36.,
       51., 61., 59.,  7.,  9., 43., 44., 14., 38., 68., 16., 11., 47.,
       63., 71., 41., 53., 39., 66., 45., 74., 64., 56., 49., 77., 67.])

In [1438]:
sharkdf.shape

(1218, 24)

In [1439]:
sharkdf.Age.isnull().sum()

0

In [1440]:
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('\w\w\w\w\w\w\w\w ','', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('-\d\d\d\d','', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('\w\w\w\w\w\w ','', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('\w\w\w \d\d\d\d','', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('\d\d\d\d','', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub(' 12-Sep','12-Sep', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub(' 07-Sep','07-Sep', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('3-Jul','03-Jul', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub(' 01-Sep','01-Sep', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub(' 14-Aug','14-Aug', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub(' 13-Sep','13-Sep', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub(' 05-Aug','05-Aug', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('  29-Jul','29-Jul', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub(' 27-Mar','27-Mar', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('    10-Jan','10-Jan', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('003-Jul','03-Jul', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('103-Jul','13-Jul', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub(' 14-Sep','14-Sep', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('19-Jul.b','19-Jul',x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('190Feb','19-Feb', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('Summer','', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('     13-Apr','13-Apr', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('     23-Apr','23-Apr', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('     27-Sep','27-Sep', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('1-Aug','01-Aug', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub(' 19-Jul to have  "on the weekend"','9-Jul', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub(' 24-Jan','24-Jan', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('Early Sep','', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('Early Jun','', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('     03-Mar','03-Mar', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('13 -Nov','13-Nov', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('Early Aug','', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('     23-Aug','23-Aug', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub(' 13-Jan','13-Jan', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('to have taken place in ','', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('     05-Jan','05-Jan', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('5-Jul','05-Jul', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('101-Aug','11-Aug', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('  29-Oct','29-Oct', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('19-Jul.a','19-Jul', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('0001-Aug','01-Aug', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('     19-Feb','19-Feb', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('Mid Jul or mid Jul','', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('04-','', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('     10-Nov','10-Nov', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('05 ','', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('13 or 30-May','', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('\n.12.15.R','', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('11-Sep to 16-Sep','', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('  21-Jun','21-Jun', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('Some time b08-Jan & 21-Jan','', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('5-Apr','05-Apr', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('4','', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub(' 28-Mar','28-Mar', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('Jul- to Sep','', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('2-May','02-May', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('205-Apr','25-Apr', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('2-Apr','02-Apr', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('005-Apr','05-Apr', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('Late Aug','', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('5-Mar','05-Mar', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('  05-Oct','05-Oct', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('Early Feb','', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('1-Apr','01-Apr', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('1-Mar','01-Mar', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('2-Feb','02-Feb', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('9-Mar','09-Mar', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('2-Apr','02-Apr', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('1-Feb','01-Feb', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('1-Jan','01-Jan', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('2-Nov','02-Nov', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('1-Nov','01-Nov', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('1-Jul','01-Jul', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('2-Sep','02-Sep', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('2-Dec','02-Dec', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('   06-Aug','06-Aug', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('2002-Apr','', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('002-Apr','02-Apr', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('105-Apr','15-Apr', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('301-Mar','31-Mar', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('001-Feb','01-Feb', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('201-Jan','21-Jan', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('002-Sep','02-Sep', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('001-Aug','01-Aug', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('203-Jul','23-Jul', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('1-Jul','01-Jul', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('1-Jun','01-Jun', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('101-Feb','11-Feb', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('101-Mar','11-Mar', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('105-Jul','15-Jul', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('002-Feb','02-Feb', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('2-Jan','02-Jan', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('101-Jan','11-Jan', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('102-Jan','12-Jan', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('001-JUl','01-JUl', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('1001-Jul','11-Jul', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('101-Jun','11-Jun', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('102-Apr','12-Apr', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('002-Apr','02-Apr', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('002-Jan','02-Jan', x))

sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub(' 001-Jul','001-Jul', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('201-Jun','21-Jun', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('001-Nov','01-Nov', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('3001-Jul','31-Jul', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('205-Jul','25-Jul', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('0001-Jul','01-Jul', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('001-Jun','01-Jun', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('1-Oct','01-Oct', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('301-Augun','31-Aug', x))
sharkdf.Date=sharkdf.Date.apply(lambda x : re.sub('201-Mar','21-Mar', x))

In [1441]:
sharkdf.Date.unique()

array(['25-Jun', '26-May', '13-May', '28-Apr', '25-Apr', '23-Apr', '',
       '05-Apr', '03-Apr', '31-Mar', '01-Mar', '09-Mar', '15-Feb',
       '28-Jan', '21-Jan', '31-Dec', '02-Nov', '13-Nov', '28-Oct',
       '09-Oct', '05-Oct', '02-Sep', '13-Sep', '10-Sep', '29-Aug',
       '23-Aug', '10-Aug', '03-Aug', '29-Jul', '22-Jul', '20-Jul',
       '09-Jul', '07-Jul', '18-Jun', '11-Jun', '02-Jun', '03-May',
       '17-Apr', '01-Apr', '02-Apr', '09-Jan', '19-Dec', '01-Dec',
       '28-Nov', '01-Nov', '201-Oct', '26-Sep', '11-Sep', '07-Sep',
       '06-Aug', '15-Jul', 'Jul', '27-Jun', '21-Jun', '01-Jun', '07-Jun',
       '05-Jun', '31-May', '29-May', '15-May', '19-Apr', '09-Apr',
       '02-Jan', '21-Dec', '20-Nov', '07-Nov', '25-Oct', '19-Oct',
       '17-Oct', 'Oct', '20-Sep', '08-Sep', '06-Sep', '05-Sep', 'Sep',
       '01-Sep', '20-Aug', '19-Aug', '18-Aug', '31-Jul', '26-Jul',
       '25-Jul', '10-Jul', '03-Jul', '02-Jul', '01-Jul', '30-Jun',
       '26-Jun', '2-Jun', '25-May', '20-May', '002-May', '26-Apr',
       '12-Apr', '18-Mar', '16-Mar', '09-Feb', '08-Feb', '30-Jan',
       '06-Jan', '03-Jan', '28-Dec', '15-Dec', '16-Nov', '301-Oct',
       '02-Oct', '09-Sep', '301-Aug', '16-Jul', '001-Jul', '09-Jun',
       '1-May', '06-May', '01-May', '209-Mar', '22-Mar', '20-Feb',
       '07-Feb', '25-Dec', '16-Dec', '11-Dec', '10-Dec', '05-Dec',
       '30-Nov', '23-Nov', '202-Nov', '26-Oct', '2-Oct', '23-Oct',
       '20-Oct', '101-Oct', '08-Oct', '06-Oct', '10-Oct', '1-Sep',
       '102-Sep', '11-Aug', '05-Aug', '28-Jul', '08-May', 'May',
       '201-Apr', '13-Apr', '10-Apr', '12-Mar', '10-Mar', '27-Feb',
       '10-Feb', '16-Jan', '30-Dec', '002-Dec', '19-Nov', 'Nov', '30-Oct',
       '27-Oct', '18-Oct', '25-Sep', '08-Aug', '30-Jul', '2-Jul',
       '06-Jul', '20-Jun', '15-Jun', '03-Jun', '102-May', '105-Mar',
       '06-Mar', 'Mar', '18-Jan', '15-Jan', '22-Oct', '30-Sep', '28-Sep',
       '16-Sep', '28-Aug', '17-Aug', '16-Aug', '12-Jun', '06-Jun',
       '21-May', '23-Mar', '28-Feb', '17-Feb', '301-Jan', '26-Jan',
       '20-Jan', '26-Dec', '27-Sep', '02-Aug', '19-Jul', '17-Jul',
       '10-Jun', '30-May', '18-May', 'Apr', '27-Mar', '13-Feb', '11-Feb',
       '06-Feb', 'Feb', '01-Feb', '12-Jan', '202-Dec', '20-Dec', '25-Nov',
       '08-Nov', '01-Aug', '16-Jun', '17-May', '16-May', '20-Mar',
       '17-Mar', '02-Mar', '001-Mar', '102-Feb', '25-Jan', '11-Jan',
       '27-Dec', '15-Sep', '30-Aug', '27-Aug', '28-Jun', '10-May',
       '07-May', '15-Apr', '08-Apr', '28-Mar', '07-Mar', '02-Feb',
       '18-Dec', '1-Dec', '06-Nov', '03-Nov', '29-Oct', '15-Oct',
       '13-Oct', '03-Sep', '26-Aug', '12-Aug', '18-Jul', '17-Jun',
       '20-Apr', '23-Jan', '07-Jan', '001-Jan', '101-Nov', '13-Aug',
       '08-Jul', '02-May', '19-May', '101-Apr', 'Jan', '02-Dec', '27-Nov',
       '15-Nov', '102-Nov', '002-Nov', '001-Oct', '2-Aug', '13-Jul',
       '28-May', '16-Apr', '109-Mar', '08-Jan', '201-Aug', '15-Aug',
       '27-Jul', '23-May', '07-Apr', '26-Feb', '16-Feb', '01-Oct',
       '005-Jul', '18-Apr', '17-Jan', '17-Nov', '03-Oct', '1-Aug',
       '202-May', '30-Apr', '001-Apr', '205-Mar', '22-Aug', '102-Dec',
       '03-Dec', '30-Mar', '26-Mar', '2-Mar', '06-Dec', '19-Sep',
       '2001-Jul', '005-Mar', '03-Feb', '201-Nov', '01-Jan', '29-Nov',
       '10-Jan', '07-Aug', '11-Mar', '09-Dec', '21-Sep', '19-Feb',
       '05-Jan', '23-Dec', '05-Nov', '25-Aug', '08-Mar', '29-Jan', 'Dec',
       '26-Nov', '12-Oct', '23-Jun', '18-Nov', '17-Sep', '009-Mar',
       '17-Dec', '12-Jul', '18-Feb', '03-Mar', '27-Jan', '29-Jun',
       '05-May', '12-30', '201-Feb', '09-Aug', '23-Jul', '23-Feb',
       '29-Apr', '13-Jun', 'Mid Aug', 'Aug', '22-Jun', 'Jun', '202-Jan',
       '05-Feb', '08-Dec', '16-Oct', '202-Sep', '02-Sep ', '13-Dec',
       '10-Nov', '19-Jan', '11-May', '07-Oct', '7-Dec', '6-Dec',
       '22-Jul-1', '202-Feb', '07-Mar or27-Mar', '2-'], dtype=object)

In [1442]:
list(sharkdf.Species.unique())

['White shark',
 "Bull shark, 6'",
 'Invalid incident',
 'Tiger shark',
 '3 m shark',
 'White shark, 2.5 m',
 'Bull shark',
 "Tiger shark, 12'",
 'Wobbegong shark',
 '3.5 m shark',
 '1.8 m shark',
 'Bull shark, 2 m',
 'Bull shark, 3 m ',
 'White shark, 4.6 m',
 '2 m shark',
 'Wobbegong shark, 1 m',
 'Tiger shark, 8 to 10 feet',
 "8' shark",
 'Questionable',
 "5' to 6' shark",
 'White shark, 3 to 3.5m ',
 'White shark, 3 m',
 "White shark, 5' to 7'",
 'Possibly a juvenile blacktip shark',
 "4' shark",
 'A small shark',
 '"A small shark"',
 "White shark, 11' to 13'",
 "White shark, 8' to 10'",
 "Bull shark, 4' to 5'",
 'Bull shark, 2m',
 'White shark, 4 m',
 'Shark involvement highly doubtful',
 "Bull shark, 5' to 7'",
 'Bull shark, 4 m',
 'Bull shark, 1 m',
 'Broadnose sevengill shark, 1.5 m',
 " 6' to 8' shark",
 'White shark, 3.5 m',
 "3' to 4' shark",
 "Tiger shark, 10'",
 "Tiger shark, 10' ",
 'Blue shark',
 "White shark, 10' to 12'",
 'dogfish shark',
 'Tawny nurse shark',
 "3' to 5' shark",
 "3' shark",
 "Said to involve an 8' shark but more likely damage caused by debris",
 '3+ m shark',
 "5' shark",
 "Nurse shark, 2'",
 'Tiger shark, 2.5 m',
 "Bronze whaler shark, 6'",
 'Galapagos shark',
 'Shark involvement not confirmed',
 "Spinner shark, 5'",
 'No shark involvement',
 "Tiger shark, 7'",
 "Tiger shark, 13' ",
 "4' to 5' shark",
 "Blacktip shark, 4' to 5'",
 'juvenile shark',
 "Tiger shark, 13'",
 "6' shark",
 "White shark, 11' to 12'",
 'Hammerhead shark.',
 'small shark',
 "White shark, 10' to 12' ",
 "Hammerhead shark. 6' to 7'",
 "Blacktip or spinner shark, 4'",
 "Thought to involve a 3' to 4' shark, but shark involvement not confirmed",
 'White shark, 3.9 to 4.2 m',
 "White shark, 7'",
 "6' to 7' shark",
 'White shark, 2m to 3 m',
 'Sandtiger shark',
 "Bull shark, 5'",
 'Bull shark, 2.5 m',
 '1m to 1.2 m shark',
 '3- to 4-foot shark',
 'White shark, 6 m',
 'Tiger shark, 8 to 12 feet',
 'Blacktip shark',
 '3.5 to 4 m shark',
 '2 m to  3 m shark',
 'Bull shark, 1.3 m',
 'White shark or oceanic whitetip shark',
 'Raggedtooth shark, 1.3 m',
 "2' shark",
 '1.5 m shark',
 '1 m shark',
 "8' to 10' shark",
 '2 white shark: 13\' & 9"8"',
 "7' shark",
 'Spinner shark',
 "4' tp 5' shark",
 "6' to 8' shark",
 " Sandbar shark, 3' to 4'",
 'Bronze whaler shark, 1.5m',
 " white shark, 15' ",
 '3 m to 4 m white shark',
 'Shark involvement prior to death not confirmed',
 'Blacktip reef shark ',
 '7-gill shark?',
 'Reported to involve a bull shark',
 'White shark, 3m ',
 "Tiger shark, 10' to 12'",
 "4' to 6' shark",
 ' Wobbegong shark, 1.6 to 1.8m ',
 'Tiger shark, 3m ',
 'Thought to involve a white shark',
 "White shark, 10 '",
 'Thought to involve a bull shark',
 "Whitetip reef shark, 4' to 6'",
 'Small bull shark',
 "Bull shark, 8'",
 "Bull shark, 6' to 8'",
 "Tiger shark, 8' to 10' ",
 'Nurse shark',
 "Tiger shark, 14'",
 'a small shark',
 'Grey nurse shark, 3m',
 'Possibly a blacktip reef shark',
 'Raggedtooth shark, 1.5 m',
 'Tiger shark, 4.8 m',
 'Bronze whaler shark, 2.5m',
 'White shark, 4m',
 'Lemon shark',
 "Tiger shark, 15'",
 '2.5 m shark',
 'Bull shark, 2m ',
 "Tiger shark, 6'",
 "10' shark",
 "2' to 3' shark",
 "Tiger shark, 8'",
 "Tiger shark, 10' to 12' ",
 "White shark, 15' to 16' ",
 '2m shark',
 "3.5' to 4' shark",
 "Lemon shark, 4' to 5' ",
 'White shark or bronze whaler',
 'White shark, 5m',
 "14' to 18'shark",
 "15' shark",
 'possibly a bull shark',
 'a small reef shark',
 'Blacktip shark ',
 'White shark, 2 m',
 '18" to 24" shark',
 'Bull shark, 3m',
 "Tiger shark, 10'  ",
 'White shark, 4m ',
 "Possibly a 5' to 6' bull shark",
 'Tawny nurse shark, 40cm',
 'White shark, 2.7 m',
 'Allegedly a 4 m tiger shark',
 'White shark, 2.5m',
 "White shark, 10'",
 'Port Jackson shark, 1m',
 '2 to 2.5 m shark',
 "6' shark, possibly a blactip or spinner shark",
 "White shark, >6'",
 'Grey reef shark ',
 'White shark, 3m to 4m',
 "Blacktip shark, 4'",
 ' Tiger shark, 2.8m',
 'reef shark, 1.5m',
 "1' to 2' shark",
 'Bull shark, 2.5m',
 '3 m to 4 m shark',
 'White shark x 2',
 'Caribbean reef shark',
 'Oceanic whitetip shark, 2.5m ',
 'Mako shark ',
 'Mako shark',
 'Oceanic whitetip shark, 2.5m, female',
 "White shark, 14' to 18' ",
 'Possibly a small blacktip shark',
 "Sandtiger shark, 4' to 5'",
 'Angel shark',
 "Lemon shark, 4'",
 '20 to 30kg shark',
 "14' shark",
 "Oceanic whitetip shark, 6'",
 'Wobbegong shark, 1.6m',
 'Invalid',
 'Zambesi shark, 2m ',
 "Sandtiger shark, 8'",
 'Thresher shark',
 'Spurdog',
 'Bull shark?',
 'Shark involvement questionable',
 "Nurse shark, 6'",
 'Thought to involve a Bronze whale shark, 2m',
 'Shark involvement probable, but not confirmed',
 '80 kg shark',
 'blacktip or spinner shark',
 'Bronze whaler shark?',
 'Thought to involve a cookie cutter shark',
 'Blue shark, 1m',
 '2.6 m shark',
 'White shark, 2.5m ',
 'Bull shark, 2.7 m ',
 "White shark, 12' ",
 'Dusky shark, 2m',
 'White shark, 3.5m',
 'Broadnose sevengill shark',
 'White shark, 4m to 5m ',
 '4 to 5m white shark',
 'Raggedtooth shark, 2m',
 '5 m white shark',
 "+3' shark",
 'Bronze whaler shark',
 "2' to 3' juvenile shark",
 "8' white shark or 7-gill shark",
 'White shark, 2m',
 "4.5 to 5' shark",
 "White shark, 15'",
 '2 small bull sharks',
 "White shark, 12' to 15'",
 'Shark involvement not confirmed; thought to be a barracuda bite',
 "1.5' to 2' shark",
 "2.5' shark",
 'A bull shark, according to some of the divers on the boat',
 'Not a shark attack; it was a hoax',
 '1.5 to 2 m shark',
 "Blacktip shark, 5'",
 'Oceanic whitetip sharks were in the vicinity',
 "Nurse shark, 2' to 3' ",
 'Possibly a spinner shark',
 "White shark, 12'",
 ' ',
 'Bronze whaler shark, 1.5 m ',
 "Bull shark, 5' ",
 'Shark involvement prior to death was not confirmed',
 "Tiger shark, 14' ",
 '"a small shark"',
 'White shark, 3m',
 '24" to 30" shark',
 "6' to 8' shark, possibly a tiger shark",
 '2.5 to 3 m shark',
 '2 to 3 m shark',
 "White shark, 12' to 15' ",
 'White shark, 5m ',
 '2 m to 3 m shark',
 "3' to 3.5' shark",
 'White shark?',
 'Angel shark, 1.2m ',
 "5' to 6' spinner or bull shark",
 "14' white shark",
 "Tiger shark, 8' to 12'",
 "Grey reef shark, 5' to 8' ",
 'Wobbegong shark, 2 m ',
 'Bronze whaler shark, a  juvenile ',
 'Raggedtooth shark, 2.5 m to 3 m ',
 "Tiger shark, 5' ",
 'Bronze whaler shark, 2 m',
 "5' to 7' shark",
 '3.5 m white shark',
 'Whitetip reef shark',
 'Raggedtooth shark, 2.5m ',
 "12' to 14' white shark",
 'Caribbean reef sharks',
 "14' to 16' white shark",
 "4 m [13'] white shark",
 'juvenile white shark',
 "1.8 m [6'] shark",
 "[4' to 5']",
 "1.8 m [6'] bull shark",
 "Mr. Burgess of ISAF announced the injury was the bite of a 1.8 m [6'], 2- to 3-year old white shark. Subsequent investigation revealed there was  no shark involvement in this incident",
 '"small shark"',
 'Raggedtooth shark',
 "Tiger shark, 3 m [10']",
 "Mako shark, 1.5 m [5'] ",
 "4 m [13'] shark",
 "6 m [20'] white shark",
 "Sandtiger shark, 2.1 m [7'] ",
 '4.5 m & 5 m white shark ',
 "5.5 m [18'] white shark",
 "2.5 m [8.25'] bull shark",
 "Tiger shark, 2.4 m to 3.7 m [8' to 12'] ",
 'Thought to involve a 2.5 m bull or tiger shark',
 "2.4 m [8'] shark",
 'Tiger shark, 1.5 m ',
 "4.9 m to 5.5 m [16' to 18'] white shark",
 "1.2 m [4'] shark",
 "1.2 m to 1.5 m [4' to 5'] shark",
 '2 sharks, 4.5 m & 3 m ',
 '9\'2" white shark',
 "0.9 m to 1.5 m [3' to 5'] shark",
 "2.4 m to 3.7 m [8' to 12'] shark",
 "1,5 m [5'] Caribbean reef shark (Carcharhinus  perezi)",
 "Mako shark, 1.8 m [6']",
 "5 m [16.5'] white shark",
 "Tiger shark, 2.4 m to 3 m [8' to 10'] ",
 "2 m [6.75'] sevengill  shark",
 "4 m to 5 m [13' to 16.5'] white shark",
 'Bull shark, 132-kg [291-lb] ',
 "Tiger shark, 4 m [13']  ?",
 '1.2 m [4\'] "grey-colored shark"',
 "4.5 m to 5.5 m [15' to 18'] white shark",
 "3.5 m [11.5'] white shark",
 'Unidentified species',
 "2.1 m  [7'] bull shark",
 "3.7 m to 4.3 m [12' to 14'] shark",
 "0.9 m to 1.2 m [3' to 4'] shark",
 'A \x93small\x94 shark',
 "Mako shark, 3 m [10']",
 "2.5 m [8.25'] white shark",
 'Species unidentified',
 "Thought to involve a 2 m [6.75'] grey nurse shark",
 'White shark, 4 m white shark',
 "3 m to 4.5 m [10' to 15'] white shark",
 "2.4 m to 3 m [8' to 10'] grey colored shark",
 "1.8 m to 2.1 m [6' to 7']\xa0 Caribbean Reef Shark ",
 'Possibly a bull shark or tiger shark',
 'Blacktip or spinner shark',
 "3.5' to 4.5' shark",
 "1.2 m [4'] blacktip shark",
 'Bull or tiger shark',
 "1' to 2' hammerhead or bonnethed shark",
 "0.9 m  to 1.2 m [3' to 4'] shark",
 "Nurse shark, 1.5 m [5'] ",
 "1.2 m [4'] blacktip or sandbar shark",
 "Bull shark, 1.8 m to 2.1 m [6' to 7'] ",
 "1.2 m to 1.5 m [4' to 5'] shark, possibly a bull shark",
 "0.9 m to 1.2 m [3' to 4'] shark; Tooth fragment recovered from hand",
 '\xa0 ',
 "1.5 to 2.5 m [5' to 8.25'] copper shark",
 "3.7 m to 4.3 m [12' to 14'] white shark",
 '1 m  shark',
 "3' blacktip shark",
 "White shark, 6m [20']",
 'Bull shark, 400-lb ',
 "3'  shark",
 "0.9 m [3'] shark",
 "Spinner shark, 3' to 4' ",
 '1.5 m [5\'] "whaler shark"',
 'C. leucas tooth fragment recovered from kayak',
 'Zambesi shark?',
 "Tiger shark, 1.8 m [6'] ",
 'Questionable incident - shark bite may have precipitated drowning',
 'A large white shark was filmed by divers on a local wreck 2 days prior to the incident.',
 'bull shark',
 "3 m [10'] bull shark",
 "3' shark, possibly  a blacktip or spinner shark",
 "Blacktip shark, 5' to 6' ",
 "1.9 m [6.5'] bull shark",
 "0.9 m  [3'] shark",
 "White shark, 2.4 m to 3 m [8' to 10'] ",
 'Possibly a juvenile blacktip or spinner shark',
 "White shark, 2.7 m [9'] ",
 "Bronze whaler shark, 2.5 m [8.25']  k",
 "6 m [20'] shark",
 "Bronze whaler shark, 2.5 m [8.25'] ",
 "1.2 m to 1.8 m [4' to 6'] shark",
 "White shark, 4.9 m [16'] ",
 "White shark, 5 m [16.5'] ",
 "Tiger shark, 1.8 m to 2.4 m [6' to 8'] ",
 "Blacktip shark, 2' ",
 "White shark, 4 m to 5 m [13' to 16.5'] ",
 'White shark, 2.5 m ',
 "60 cm to 90 cm [2' to 3'] shark",
 "White shark, 3.5 m [11.5']  male ",
 "1.5 m [5'] shark",
 "Tiger shark, 3 m [10'] ",
 "A 2' shark was seen in the area by witnesses",
 "Thought to involve a 2.7 m [9'], 400-lb bull shark",
 'Tiger shark, 3.7 m to 4.5 m [12\' to 14\'9"]  ',
 "Blacktip shark, 2.4 m to 3 m [8' to 10'] ",
 "Tiger shark, 0.9 m to 1.5 m [3' to 5'] ?",
 "Nurse shark, 1.2 m [4'] ",
 "0.9 m [3'] shark,  probably a blacktip or spinner shark",
 "Blacktip shark, 1.2 m to 1.8 m [4' to 6'] ",
 "Shortfin mako shark, 3 m to 3.4 m [10' to 11'] ",
 '1.3 to 1.6 m shark',
 "2.7 m [9']  bull shark or Caribbean reef shark",
 "White shark, 3 m to 5 m [10' to 16.5'] ",
 "Bull shark, 2.1 m [7']",
 'Grey reef shark, 1.5 m ',
 '3 bull sharks',
 "3.7 m to 4.6 m [12' to 15'] shark seen in the vicinity",
 "White shark, 4.6 m [15'] ",
 'Possibly a white shark',
 'A "small shark"',
 "White shark, 5 m to 6 m [16.5' to 20'] ",
 "Caribbean reef shark, 1.2 m to 1.5 m [4' to 5'] ",
 "White shark, 4.9 m [16']",
 'Thought to involve a 5.5 m white shark named Kong',
 "3 m to 4 m [10' to 13'] white shark",
 "Lemon shark, 1.5 m [5'], identified  by the surfer",
 "1.8 m [6'] shark, possibly a blacktip",
 "3 m [10'] shark",
 "3 m [10'] white shark",
 'Small dusky shark or blackfin shark',
 "Tiger shark, 4 m to 4.3 m [13' to 14'] ",
 'Possibly a blacktip shark',
 '"juvenile shark"',
 '4.5 m white shark',
 "Tiger shark, 2.7m  [9']",
 "1.2 m [4'] shark (spinner shark?)",
 'Possibly a sand shark',
 "1.8 m to 2.1 m [6' to 7'] shark",
 'Tiger shark, 4.5 m [14\'9"]',
 "3 m to 5 m [10' to 16.5'] white shark",
 '"a young shark"',
 "Tiger shark, 2.4 m [8'] ",
 "1.8 m to 2.1 m [6' to 7'] hammerhead shark",
 "2.5 m [8.25'] white shark ",
 "60 cm to 90 cm [2' to 3'] blacktip or spinner shark",
 'Possibly a tiger shark',
 'Tiger shark, 300-kg [662-lb] ',
 '4 m shark',
 "1.2 m to 1.5 m [4' to 5']   shark",
 "Tiger shark, 3.7 m [12'] ",
 'Bronze whaler shark, 2 m ',
 "5 m to 5.5 m [16.5' to 18'] white shark",
 "2.7 m [9'] shark",
 'Thought to involve a small sand shark',
 'Small shark',
 "3 to 3.5 m [10' to 11.5'] bull shark",
 '3.6 m [11\'9"] white shark',
 '1.3 m [4\'3"] shark',
 'Tiger shark caught 6 days later with diver\x92s remains in its gut',
 ">6 m [20'] white shark",
 "1.8 m [6'] blacktip shark or Caribbean reef shark",
 "5.5 m to 6 m [18' to 20']  white shark",
 "1.8 m to 2.4 m [6' to 8'] shark, tooth fragments recovered ",
 "Remains recovered from 5.5 m [18'] white shark",
 "Tiger shark, 3.7 m [12'], (tooth fragment recovered from wound)",
 "Tiger shark, 3 m to 4.9 m [10' to 16'] ",
 "Mako shark, 1.8 m [6']  ",
 "6' to 7' blacktip shark",
 '5 m to 6 m white shark',
 'Unidentified shark',
 "Tiger shark, 3 m to 3.7 m [10' to 12'] ",
 "Tiger shark, 4.3 m [14'] ",
 '4.2 m white shark',
 '4 m white shark',
 'Bull shark or lemon shark',
 '>2 m shark',
 "5 m [16.5'] white shark, identification by K. Nakaya",
 "Said to involve a 6 m to 7 m [20' to 23'] white shark",
 'Questionable incident',
 "Bronze whaler shark, 2.3 m [7.5'] ",
 "Zambesi shark, 1.7 m [5.5'] ",
 "Possibly a 1.5 m [5'] blacktip shark",
 "Tiger shark, 2.4 m 3.4 m [8' to 11']  ",
 "5 m to 6 m [16.5' to 20'] white shark",
 'sand shark',
 "Tiger shark, 3 to 4 m [10' to 13'] ",
 "2.7 m [9'] bull or lemon shark",
 "Tiger shark, >3 m [10']",
 "1.8 m [6'] shark ",
 "4' spinner shark",
 "1.8 m to 2.4 m [6' to 8'] shark",
 "5 m  [16.5'] white shark",
 "2.5 m to 3 m [8.25' to 10']  white shark",
 '4.5 m [14\'9"] white shark',
 "2.3 m [7.5'] white shark, identified by M. Smale",
 'Tiger shark, 3 m ',
 "2.7 m [9'] white shark",
 'White shark, identified by tooth pattern',
 "4 m to 5 m [13' to 16.5']  white shark",
 ">3.4 m [11'] white shark",
 "Bronze whaler shark, 3 m [10'] ",
 "2 m [6.75'] white shark",
 "Tiger shark, 4 m [13'] ",
 "2.4 m to 3 m [8' to 10'] white shark",
 'Sand shark?',
 "1.5 m to 2 m [5' to 6.75'] shark",
 'Zambezi shark (tooth fragments recovered)',
 '1.5 m copper shark',
 "1.8 m [6'] blacktip shark",
 "3.5 m [11.5']  white shark",
 '5.7 m white shark',
 '4.3 m shark',
 ">2.5 m [8.25'] white shark",
 "1.8 m to 2.1 m [6' to 7'] spinner or blacktip shark",
 "Lemon shark, 1.8 m to 2.4 m [6' to 8'], tooth fragment recovered",
 '1.6 m shark',
 "1.2 m [4'] dusky shark",
 '>1 m shark',
 ">2.4 m [8'] white shark",
 "Raggedtooth shark, 2 m [6.75'] ",
 'Bronze whaler shark, 3.5 m ',
 "2 m to 2.5 m [6.75'  to 8.25'] sixgill or sevengill shark",
 'Possibly a small hammerhead shark',
 '3 m to 3.6 m  [10\' to 11\'9"] white shark',
 '3.5 m white shark, tooth fragments recovered',
 'Tiger shark, 4 m ',
 'Shark involvement not confirmed; officials considered barracua',
 '4.5 m to 5 m white shark',
 "2.4 m [8'] white shark",
 "1.2 m to 1.5 m [4' to 5'] hammerhead shark",
 " 1.5 m [5'] dusky shark",
 'Raggedtooth shark, 1 m ',
 'Raggedtooth shark, >1 m ',
 "Tiger shark, 5 m [16.5']",
 "6' blacktip shark",
 "Raggedtooth shark, 1.5 m [5'] (tooth fragment recovered)",
 "1.8 m [6'] Zambezi shark",
 'Believed to involve a 2.8 m [9\'3"] white shark',
 'Questionable incident; reported as shark attack but thought to involve a pinniped instead ',
 "2.4 m [8'] white shark, species identity confirmed by tooth fragment",
 "4.5 m to 5.5 m [14.7' to 18'] white shark",
 "2.4 m [8'] white shark, species identity confirmed by witnesses & tooth pattern in surfboard",
 'Mako shark (tooth fragments recovered)',
 "Possibly a  1.8 m [6'] Zambezi shark",
 '6 m  white shark',
 "Raggedtooth shark, 2.5 m [8.25'] ",
 "Tiger shark, 2.1 m [7']",
 "1.2 m to 1.5 m [4' to 5'] bull, sandbar or dusky shark",
 'C. maculpinnis or C. limbatus',
 'Juvenile dusky or blacktip shark',
 "1.8 m to 2.4 m [6' to 8'] hammerhead shark",
 'Tiger shark, 2.5 m ',
 "3.5 m [11.5'] shark",
 '2.8 m [9\'3"] white shark',
 '2 m [6\'9"] Zambesi shark',
 'Raggedtooth shark, 2 m [6\'9"] ',
 "White shark, 2.5 m [8.25']  ",
 "White shark, 2.3 m [7.5'], tooth fragment recovered",
 "White shark, 3.7 m [12'] ",
 'Thought to involve a blacktip shark',
 "White shark, 5.5 m [18'] ",
 "White shark, 3 m [10'] k",
 "2.1 m [7'] lemon shark or bull shark",
 "White shark, 3 m to 4 m [10' to 13'] ",
 "Tiger shark, 6' ",
 'White shark, 4.5 m ',
 'Juvenile dusky shark',
 "White shark, 2.4 m [8']",
 "White shark, 5.8 m [19'] ",
 'White shark, 5m to 6m',
 "White shark, 3 m [10'] ",
 "White shark, 5.5 m to 6 m [18' to 20'] ",
 'White shark, 4 m to 5 m ',
 "White shark, 5 m to 6 m [16.5 to 20'] ",
 "White shark, 5 m [16.5']",
 "2 m to 2.5 m [6.75'  to 8.25'] shark",
 "7' to 8' bull shark",
 "White shark, 4.4 m to 5 m [14.5' to 16.5'] ",
 'Zambesi shark',
 "White shark, 2.5 m [8.25'] ",
 "White shark, 3 m [10']rk",
 "White shark, 5 m to 6 m [16.5' to 20']  ",
 "Grey nurse shark, 11'",
 "White shark, 3 m [10'], species identity confirmed by witnesses & tooth pattern in leg & board ",
 '1.8 to 2 m C. albimarginatus',
 'Raggedtooth shark, 2 m [6\'9"], 5-year-old, captive female ',
 "White shark, 4.3 m 4.9 m [14' to 16'] ",
 'White shark, identified by tooth fragments in surfboard',
 "White shark, 4.3 m [14'], (tooth fragment recovered)",
 "White shark, 4 m [13'] ",
 "2.7 m [9'] silky shark",
 'small blacktip shark',
 "5' blue shark",
 'Nurse shark, 106 cm, 28-lb, male ',
 'Nurse shark, 1 m ',
 'Grey nurse shark',
 "3.7 m [12'] shark",
 "Bronze whaler shark, 2.1 m [7'], a tooth was embedded in the speargun ",
 "Mako shark, 1.9 m [6.5'] ",
 'Spinner or blacktip sharks',
 "Local authorities speculated that the water was too cold for sharks, but a 2.1 m [7'], 200-lb pregnant sandbar shark was caught next day",
 "1.2 m [4'] hammerhead shark",
 "White shark, 2.5 m [8.25'], an immature female, previously injured",
 "1.5 m to 1.8 m [5' to 6'] Zambesi shark",
 '1.8 m to 2 m [6\' to 6\'9"] shark',
 'Hammerhead shark',
 "Grey nurse shark, 2.4 m [8'] ",
 '300-kg [662-lb] shark',
 'Tiger shark, tooth fragment recovered',
 'Raggedtooth shark ',
 "White shark, 2.4 m [8'] ",
 "Grey nurse shark, 1.8 m [6']",
 "1.8 to 2.4 m [6' to 8'] shark",
 "1.7 m [5.5'] shark",
 "White shark, 1.5 m [5'] k",
 "White shark, 3 m to 3.7 m [10' to 12'] ",
 'White shark (tooth fragment recovered)',
 "1.8 m [6']  shark",
 'Dusky shark, 1 m ',
 '300- to 400-lb Zambesi shark',
 ">1.2 m [4'] tiger shark",
 'Dooley believed his Injury was caused by stingray (Dasyatidae family)',
 '500-lb shark',
 "5.5 m [18'] shark",
 'White shark, 3 m ',
 'Hand found in gut of 2.9 m to 3.3 m [9\'7" to 10\'11"] Galapagos shark, C. galapagensis',
 "3.7 to 4.5 m [12' to 15'] shark seen in vicinity",
 "White shark, 2.1 m [7'] ",
 'Tooth fragments of \x93whaler\x94 shark were recovered, a bull shark, according to Edwards',
 'Zambesi shark, 2 m [6\'9"] ',
 "White shark, 4.3 m [14'] (or bronze whaler)",
 "White shark, 4.3 m to 4.9m [14' to 16']",
 " Blacktip shark, C. maculipinnis. 1.9 m to 2.1 m [6.5' to 7'] ",
 "Horn shar,k Heterodontus francisci, 1.2 m [4'] ",
 'Unknown',
 " Sevengill  shark, 1.2 m [4'] ",
 "Zambesi shark, 1.2 m [4'] ",
 '60 cm  shark ',
 "Bronze whaler shark, 2.1 m [7'] shark",
 '36"  shark',
 '43" shark',
 'Hammerhead shark, 500-llb ',
 "Grey reef shark, 1.8 m [6'] grey reef shark, identified by Dr. L.P. L. Schultz based on photographs; identified as C. melanopterus by Stewart",
 "2.1 m [7'], 90-kg shark",
 'White shark, based on bite pattern',
 "White shark, 3 m [10'], tooth fragment from wounds identified as that of a white shark",
 'Grey nurse shark, 1m ',
 'Lemon shark, 1164 mm, immature male, identified by  V.G. Springer',
 '"sand shark"',
 "Mako shark, 1.8 m to 2.1 m [6' to 7']  with hook & wire leader caught in mouth",
 "Dusky shark, 2.7 m [9'] dusky shark C. obscurus identified by S. Springer on tooth recovered",
 "White shark, 2.1 m [7']  based on tooth pattern",
 "1.2 m [4'], possibly  larger shark",
 'According to Benjamin, the injury was inflicted by a barracuda, not a shark',
 "3 m to 4.3 m [10' to 14'] shark",
 "Blue shark, 1.5 m [5'] ",
 "White shark, 5 m [16.5'], identified by Dr. W. I. Follett on tooth marks",
 "Tiger shark, 1.8 m [6']",

In [1443]:
sharkdf['Species']=sharkdf['Species'].fillna('Unknown')

In [1444]:
sharkdf['Species1']=sharkdf.Species.apply(lambda x : re.sub('[0-9]','', x)) #quito los nÃºmeros
sharkdf['Species1']=sharkdf.Species.apply(lambda x : re.sub('[\W]','', x))  
sharkdf['Species1']=sharkdf.Species.apply(lambda x : re.sub('[a-z ]*?white[a-z ]* ?\W?','White', x))
sharkdf['Species1']=sharkdf.Species.apply(lambda x : re.sub('[a-z ]*?blue[a-z ]* ?\W?','Blue', x))
sharkdf['Species1']=sharkdf.Species.apply(lambda x : re.sub('[a-z ]*?lemon[a-z ]* ?\W?','Lemon', x))
sharkdf['Species1']=sharkdf.Species.apply(lambda x : re.sub('[a-z ]*?bull[a-z ]* ?\W?','Bull', x))
sharkdf['Species1']=sharkdf.Species.apply(lambda x : re.sub('[a-z ]*?mako[a-z ]* ?\W?','Mako', x))
sharkdf['Species1']=sharkdf.Species.apply(lambda x : re.sub('[a-z ]*?blacktip[a-z ]* ?\W?','Blacktip', x))
sharkdf['Species1']=sharkdf.Species.apply(lambda x : re.sub('[a-z ]*?nurse[a-z ]* ?\W?','Nurse', x))
sharkdf['Species1']=sharkdf.Species.apply(lambda x : re.sub('[a-z ]*?goblin[a-z ]* ?\W?','Goblin', x))
sharkdf['Species1']=sharkdf.Species.apply(lambda x : re.sub('[a-z ]*?spinner[a-z ]* ?\W?','Spinner', x))
sharkdf['Species1']=sharkdf.Species.apply(lambda x : re.sub('[a-z ]*?dusky[a-z ]* ?\W?','Dusky', x))
sharkdf['Species1']=sharkdf.Species.apply(lambda x : re.sub('[a-z ]*?galapagos[a-z ]* ?\W?','Galapagos', x))
sharkdf['Species1']=sharkdf.Species.apply(lambda x : re.sub('[a-z ]*?leopard[a-z ]* ?\W?','Leopard', x))
sharkdf['Species1']=sharkdf.Species.apply(lambda x : re.sub('[a-z ]*?bronze[a-z ]* ?\W?','Bronze', x))
sharkdf['Species1']=sharkdf.Species.apply(lambda x : re.sub('[a-z ]*?raggedtooth[a-z ]* ?\W?','Raggedtooth', x))
sharkdf['Species1']=sharkdf.Species.apply(lambda x : re.sub('[a-z ]*?grey[a-z ]* ?\W?','Grey', x))
sharkdf['Species1']=sharkdf.Species.apply(lambda x : re.sub('[a-z ]*?hammerhead[a-z ]* ?\W?','Hammerhead', x))
sharkdf['Species1']=sharkdf.Species.apply(lambda x : re.sub('[a-z ]*?angel[a-z ]* ?\W?','Angel', x))
sharkdf['Species1']=sharkdf.Species.apply(lambda x : re.sub('[a-z ]*?reef[a-z ]* ?\W?','Reef', x))
sharkdf['Species1']=sharkdf.Species.apply(lambda x : re.sub('[a-z ]*?dogfish[a-z ]* ?\W?','Dogfish', x))
sharkdf['Species1']=sharkdf.Species.apply(lambda x : re.sub('[a-z ]*?carpet[a-z ]* ?\W?','Carpet', x))
sharkdf['Species1']=sharkdf.Species.apply(lambda x : re.sub('[a-z ]*?banjo[a-z ]* ?\W?','Banjo', x))
sharkdf['Species1']=sharkdf.Species.apply(lambda x : re.sub('[a-z ]*?cleucas[a-z ]* ?\W?','Cleucas', x))
sharkdf['Species1']=sharkdf.Species.apply(lambda x : re.sub('[a-z ]*?spurdog[a-z ]* ?\W?','Spurdog', x))
sharkdf['Species1']=sharkdf.Species.apply(lambda x : re.sub('[a-z ]*?bull[a-z ]* ?\W?','Bull', x))
sharkdf['Species1']=sharkdf.Species.apply(lambda x : re.sub('[a-z ]*?[san]?[d]tiger[a-z ]* ?\W?','Tiger', x))

In [1445]:
sharkdf.Species1.unique()

array(['White shark', "Bull shark, 6'", 'Invalid incident', 'Tiger shark',
       '3 m shark', 'White shark, 2.5 m', 'Bull shark',
       "Tiger shark, 12'", 'Wobbegong shark', '3.5 m shark',
       '1.8 m shark', 'Bull shark, 2 m', 'Bull shark, 3 m ',
       'White shark, 4.6 m', '2 m shark', 'Wobbegong shark, 1 m',
       'Tiger shark, 8 to 10 feet', "8' shark", 'Questionable',
       "5' to 6' shark", 'White shark, 3 to 3.5m ', 'White shark, 3 m',
       "White shark, 5' to 7'", 'Possibly a juvenile blacktip shark',
       "4' shark", 'A small shark', '"A small shark"',
       "White shark, 11' to 13'", "White shark, 8' to 10'",
       "Bull shark, 4' to 5'", 'Bull shark, 2m', 'White shark, 4 m',
       'Shark involvement highly doubtful', "Bull shark, 5' to 7'",
       'Bull shark, 4 m', 'Bull shark, 1 m',
       'Broadnose sevengill shark, 1.5 m', " 6' to 8' shark",
       'White shark, 3.5 m', "3' to 4' shark", "Tiger shark, 10'",
       "Tiger shark, 10' ", 'Blue shark', "White shark, 10' to 12'",
       'dogfish shark', 'Tawny nurse shark', "3' to 5' shark", "3' shark",
       "Said to involve an 8' shark but more likely damage caused by debris",
       '3+ m shark', "5' shark", "Nurse shark, 2'", 'Tiger shark, 2.5 m',
       "Bronze whaler shark, 6'", 'Galapagos shark',
       'Shark involvement not confirmed', "Spinner shark, 5'",
       'No shark involvement', "Tiger shark, 7'", "Tiger shark, 13' ",
       "4' to 5' shark", "Blacktip shark, 4' to 5'", 'juvenile shark',
       "Tiger shark, 13'", "6' shark", "White shark, 11' to 12'",
       'Hammerhead shark.', 'small shark', "White shark, 10' to 12' ",
       "Hammerhead shark. 6' to 7'", "Blacktip or spinner shark, 4'",
       "Thought to involve a 3' to 4' shark, but shark involvement not confirmed",
       'White shark, 3.9 to 4.2 m', "White shark, 7'", "6' to 7' shark",
       'White shark, 2m to 3 m', 'STiger', "Bull shark, 5'",
       'Bull shark, 2.5 m', '1m to 1.2 m shark', '3- to 4-foot shark',
       'White shark, 6 m', 'Tiger shark, 8 to 12 feet', 'Blacktip shark',
       '3.5 to 4 m shark', '2 m to  3 m shark', 'Bull shark, 1.3 m',
       'White shark or oceanic whitetip shark',
       'Raggedtooth shark, 1.3 m', "2' shark", '1.5 m shark', '1 m shark',
       "8' to 10' shark", '2 white shark: 13\' & 9"8"', "7' shark",
       'Spinner shark', "4' tp 5' shark", "6' to 8' shark",
       " Sandbar shark, 3' to 4'", 'Bronze whaler shark, 1.5m',
       " white shark, 15' ", '3 m to 4 m white shark',
       'Shark involvement prior to death not confirmed',
       'Blacktip reef shark ', '7-gill shark?',
       'Reported to involve a bull shark', 'White shark, 3m ',
       "Tiger shark, 10' to 12'", "4' to 6' shark",
       ' Wobbegong shark, 1.6 to 1.8m ', 'Tiger shark, 3m ',
       'Thought to involve a white shark', "White shark, 10 '",
       'Thought to involve a bull shark', "Whitetip reef shark, 4' to 6'",
       'Small bull shark', "Bull shark, 8'", "Bull shark, 6' to 8'",
       "Tiger shark, 8' to 10' ", 'Nurse shark', "Tiger shark, 14'",
       'a small shark', 'Grey nurse shark, 3m',
       'Possibly a blacktip reef shark', 'Raggedtooth shark, 1.5 m',
       'Tiger shark, 4.8 m', 'Bronze whaler shark, 2.5m',
       'White shark, 4m', 'Lemon shark', "Tiger shark, 15'",
       '2.5 m shark', 'Bull shark, 2m ', "Tiger shark, 6'", "10' shark",
       "2' to 3' shark", "Tiger shark, 8'", "Tiger shark, 10' to 12' ",
       "White shark, 15' to 16' ", '2m shark', "3.5' to 4' shark",
       "Lemon shark, 4' to 5' ", 'White shark or bronze whaler',
       'White shark, 5m', "14' to 18'shark", "15' shark",
       'possibly a bull shark', 'a small reef shark', 'Blacktip shark ',
       'White shark, 2 m', '18" to 24" shark', 'Bull shark, 3m',
       "Tiger shark, 10'  ", 'White shark, 4m ',
       "Possibly a 5' to 6' bull shark", 'Tawny nurse shark, 40cm',
       'White shark, 2.7 m', 'Allegedly a 4 m tiger shark',
       'White shark, 2.5m', "White shark, 10'", 'Port Jackson shark, 1m',
       '2 to 2.5 m shark',
       "6' shark, possibly a blactip or spinner shark",
       "White shark, >6'", 'Grey reef shark ', 'White shark, 3m to 4m',
       "Blacktip shark, 4'", ' Tiger shark, 2.8m', 'reef shark, 1.5m',
       "1' to 2' shark", 'Bull shark, 2.5m', '3 m to 4 m shark',
       'White shark x 2', 'Caribbean reef shark',
       'Oceanic whitetip shark, 2.5m ', 'Mako shark ', 'Mako shark',
       'Oceanic whitetip shark, 2.5m, female', "White shark, 14' to 18' ",
       'Possibly a small blacktip shark', "STiger 4' to 5'",
       'Angel shark', "Lemon shark, 4'", '20 to 30kg shark', "14' shark",
       "Oceanic whitetip shark, 6'", 'Wobbegong shark, 1.6m', 'Invalid',
       'Zambesi shark, 2m ', "STiger 8'", 'Thresher shark', 'Spurdog',
       'Bull shark?', 'Shark involvement questionable', "Nurse shark, 6'",
       'Thought to involve a Bronze whale shark, 2m',
       'Shark involvement probable, but not confirmed', '80 kg shark',
       'blacktip or spinner shark', 'Bronze whaler shark?',
       'Thought to involve a cookie cutter shark', 'Blue shark, 1m',
       '2.6 m shark', 'White shark, 2.5m ', 'Bull shark, 2.7 m ',
       "White shark, 12' ", 'Dusky shark, 2m', 'White shark, 3.5m',
       'Broadnose sevengill shark', 'White shark, 4m to 5m ',
       '4 to 5m white shark', 'Raggedtooth shark, 2m', '5 m white shark',
       "+3' shark", 'Bronze whaler shark', "2' to 3' juvenile shark",
       "8' white shark or 7-gill shark", 'White shark, 2m',
       "4.5 to 5' shark", "White shark, 15'", '2 small bull sharks',
       "White shark, 12' to 15'",
       'Shark involvement not confirmed; thought to be a barracuda bite',
       "1.5' to 2' shark", "2.5' shark",
       'A bull shark, according to some of the divers on the boat',
       'Not a shark attack; it was a hoax', '1.5 to 2 m shark',
       "Blacktip shark, 5'",
       'Oceanic whitetip sharks were in the vicinity',
       "Nurse shark, 2' to 3' ", 'Possibly a spinner shark',
       "White shark, 12'", ' ', 'Bronze whaler shark, 1.5 m ',
       "Bull shark, 5' ",
       'Shark involvement prior to death was not confirmed',
       "Tiger shark, 14' ", '"a small shark"', 'White shark, 3m',
       '24" to 30" shark', "6' to 8' shark, possibly a tiger shark",
       '2.5 to 3 m shark', '2 to 3 m shark', "White shark, 12' to 15' ",
       'White shark, 5m ', '2 m to 3 m shark', "3' to 3.5' shark",
       'White shark?', 'Angel shark, 1.2m ',
       "5' to 6' spinner or bull shark", "14' white shark",
       "Tiger shark, 8' to 12'", "Grey reef shark, 5' to 8' ",
       'Wobbegong shark, 2 m ', 'Bronze whaler shark, a  juvenile ',
       'Raggedtooth shark, 2.5 m to 3 m ', "Tiger shark, 5' ",
       'Bronze whaler shark, 2 m', "5' to 7' shark", '3.5 m white shark',
       'Whitetip reef shark', 'Raggedtooth shark, 2.5m ',
       "12' to 14' white shark", 'Caribbean reef sharks',
       "14' to 16' white shark", "4 m [13'] white shark",
       'juvenile white shark', "1.8 m [6'] shark", "[4' to 5']",
       "1.8 m [6'] bull shark",
       "Mr. Burgess of ISAF announced the injury was the bite of a 1.8 m [6'], 2- to 3-year old white shark. Subsequent investigation revealed there was  no shark involvement in this incident",
       '"small shark"', 'Raggedtooth shark', "Tiger shark, 3 m [10']",
       "Mako shark, 1.5 m [5'] ", "4 m [13'] shark",
       "6 m [20'] white shark", "STiger 2.1 m [7'] ",
       '4.5 m & 5 m white shark ', "5.5 m [18'] white shark",
       "2.5 m [8.25'] bull shark",
       "Tiger shark, 2.4 m to 3.7 m [8' to 12'] ",
       'Thought to involve a 2.5 m bull or tiger shark',
       "2.4 m [8'] shark", 'Tiger shark, 1.5 m ',
       "4.9 m to 5.5 m [16' to 18'] white shark", "1.2 m [4'] shark",
       "1.2 m to 1.5 m [4' to 5'] shark", '2 sharks, 4.5 m & 3 m ',
       '9\'2" white shark', "0.9 m to 1.5 m [3' to 5'] shark",
       "2.4 m to 3.7 m [8' to 12'] shark",
       "1,5 m [5'] Caribbean reef shark (Carcharhinus  perezi)",
       "Mako shark, 1.8 m [6']", "5 m [16.5'] white shark",
       "Tiger shark, 2.4 m to 3 m [8' to 10'] ",
       "2 m [6.75'] sevengill  shark",
       "4 m to 5 m [13' to 16.5'] white shark",
       'Bull shark, 132-kg [291-lb] ', "Tiger shark, 4 m [13']  ?",
       '1.2 m [4\'] "grey-colored shark"',
       "4.5 m to 5.5 m [15' to 18'] white shark",
       "3.5 m [11.5'] white shark", 'Unidentified species',
       "2.1 m  [7'] bull shark", "3.7 m to 4.3 m [12' to 14'] shark",
       "0.9 m to 1.2 m [3' to 4'] shark", 'A \x93small\x94 shark',
       "Mako shark, 3 m [10']", "2.5 m [8.25'] white shark",
       'Species unidentified',
       "Thought to involve a 2 m [6.75'] grey nurse shark",
       'White shark, 4 m white shark',
       "3 m to 4.5 m [10' to 15'] white shark",
       "2.4 m to 3 m [8' to 10'] grey colored shark",
       "1.8 m to 2.1 m [6' to 7']\xa0 Caribbean Reef Shark ",
       'Possibly a bull shark or tiger shark',
       'Blacktip or spinner shark', "3.5' to 4.5' shark",
       "1.2 m [4'] blacktip shark", 'Bull or tiger shark',
       "1' to 2' hammerhead or bonnethed shark",
       "0.9 m  to 1.2 m [3' to 4'] shark", "Nurse shark, 1.5 m [5'] ",
       "1.2 m [4'] blacktip or sandbar shark",
       "Bull shark, 1.8 m to 2.1 m [6' to 7'] ",
       "1.2 m to 1.5 m [4' to 5'] shark, possibly a bull shark",
       "0.9 m to 1.2 m [3' to 4'] shark; Tooth fragment recovered from hand",
       '\xa0 ', "1.5 to 2.5 m [5' to 8.25'] copper shark",
       "3.7 m to 4.3 m [12' to 14'] white shark", '1 m  shark',
       "3' blacktip shark", "White shark, 6m [20']",
       'Bull shark, 400-lb ', "3'  shark", "0.9 m [3'] shark",
       "Spinner shark, 3' to 4' ", '1.5 m [5\'] "whaler shark"',
       'C. leucas tooth fragment recovered from kayak', 'Zambesi shark?',
       "Tiger shark, 1.8 m [6'] ",
       'Questionable incident - shark bite may have precipitated drowning',
       'A large white shark was filmed by divers on a local wreck 2 days prior to the incident.',
       'bull shark', "3 m [10'] bull shark",
       "3' shark, possibly  a blacktip or spinner shark",
       "Blacktip shark, 5' to 6' ", "1.9 m [6.5'] bull shark",
       "0.9 m  [3'] shark", "White shark, 2.4 m to 3 m [8' to 10'] ",
       'Possibly a juvenile blacktip or spinner shark',
       "White shark, 2.7 m [9'] ",
       "Bronze whaler shark, 2.5 m [8.25']  k", "6 m [20'] shark",
       "Bronze whaler shark, 2.5 m [8.25'] ",
       "1.2 m to 1.8 m [4' to 6'] shark", "White shark, 4.9 m [16'] ",
       "White shark, 5 m [16.5'] ",
       "Tiger shark, 1.8 m to 2.4 m [6' to 8'] ", "Blacktip shark, 2' ",
       "White shark, 4 m to 5 m [13' to 16.5'] ", 'White shark, 2.5 m ',
       "60 cm to 90 cm [2' to 3'] shark",
       "White shark, 3.5 m [11.5']  male ", "1.5 m [5'] shark",
       "Tiger shark, 3 m [10'] ",
       "A 2' shark was seen in the area by witnesses",
       "Thought to involve a 2.7 m [9'], 400-lb bull shark",
       'Tiger shark, 3.7 m to 4.5 m [12\' to 14\'9"]  ',
       "Blacktip shark, 2.4 m to 3 m [8' to 10'] ",
       "Tiger shark, 0.9 m to 1.5 m [3' to 5'] ?",
       "Nurse shark, 1.2 m [4'] ",
       "0.9 m [3'] shark,  probably a blacktip or spinner shark",
       "Blacktip shark, 1.2 m to 1.8 m [4' to 6'] ",
       "Shortfin mako shark, 3 m to 3.4 m [10' to 11'] ",
       '1.3 to 1.6 m shark',
       "2.7 m [9']  bull shark or Caribbean reef shark",
       "White shark, 3 m to 5 m [10' to 16.5'] ",
       "Bull shark, 2.1 m [7']", 'Grey reef shark, 1.5 m ',
       '3 bull sharks',
       "3.7 m to 4.6 m [12' to 15'] shark seen in the vicinity",
       "White shark, 4.6 m [15'] ", 'Possibly a white shark',
       'A "small shark"', "White shark, 5 m to 6 m [16.5' to 20'] ",
       "Caribbean reef shark, 1.2 m to 1.5 m [4' to 5'] ",
       "White shark, 4.9 m [16']",
       'Thought to involve a 5.5 m white shark named Kong',
       "3 m to 4 m [10' to 13'] white shark",
       "Lemon shark, 1.5 m [5'], identified  by the surfer",
       "1.8 m [6'] shark, possibly a blacktip", "3 m [10'] shark",
       "3 m [10'] white shark", 'Small dusky shark or blackfin shark',
       "Tiger shark, 4 m to 4.3 m [13' to 14'] ",
       'Possibly a blacktip shark', '"juvenile shark"',
       '4.5 m white shark', "Tiger shark, 2.7m  [9']",
       "1.2 m [4'] shark (spinner shark?)", 'Possibly a sand shark',
       "1.8 m to 2.1 m [6' to 7'] shark", 'Tiger shark, 4.5 m [14\'9"]',
       "3 m to 5 m [10' to 16.5'] white shark", '"a young shark"',
       "Tiger shark, 2.4 m [8'] ",
       "1.8 m to 2.1 m [6' to 7'] hammerhead shark",
       "2.5 m [8.25'] white shark ",
       "60 cm to 90 cm [2' to 3'] blacktip or spinner shark",
       'Possibly a tiger shark', 'Tiger shark, 300-kg [662-lb] ',
       '4 m shark', "1.2 m to 1.5 m [4' to 5']   shark",
       "Tiger shark, 3.7 m [12'] ", 'Bronze whaler shark, 2 m ',
       "5 m to 5.5 m [16.5' to 18'] white shark", "2.7 m [9'] shark",
       'Thought to involve a small sand shark', 'Small shark',
       "3 to 3.5 m [10' to 11.5'] bull shark",
       '3.6 m [11\'9"] white shark', '1.3 m [4\'3"] shark',
       'Tiger shark caught 6 days later with diver\x92s remains in its gut',
       ">6 m [20'] white shark",
       "1.8 m [6'] blacktip shark or Caribbean reef shark",
       "5.5 m to 6 m [18' to 20']  white shark",
       "1.8 m to 2.4 m [6' to 8'] shark, tooth fragments recovered ",
       "Remains recovered from 5.5 m [18'] white shark",
       "Tiger shark, 3.7 m [12'], (tooth fragment recovered from wound)",
       "Tiger shark, 3 m to 4.9 m [10' to 16'] ",
       "Mako shark, 1.8 m [6']  ", "6' to 7' blacktip shark",
       '5 m to 6 m white shark', 'Unidentified shark',
       "Tiger shark, 3 m to 3.7 m [10' to 12'] ",
       "Tiger shark, 4.3 m [14'] ", '4.2 m white shark',
       '4 m white shark', 'Bull shark or lemon shark', '>2 m shark',
       "5 m [16.5'] white shark, identification by K. Nakaya",
       "Said to involve a 6 m to 7 m [20' to 23'] white shark",
       'Questionable incident', "Bronze whaler shark, 2.3 m [7.5'] ",
       "Zambesi shark, 1.7 m [5.5'] ",
       "Possibly a 1.5 m [5'] blacktip shark",
       "Tiger shark, 2.4 m 3.4 m [8' to 11']  ",
       "5 m to 6 m [16.5' to 20'] white shark", 'sand shark',
       "Tiger shark, 3 to 4 m [10' to 13'] ",
       "2.7 m [9'] bull or lemon shark", "Tiger shark, >3 m [10']",
       "1.8 m [6'] shark ", "4' spinner shark",
       "1.8 m to 2.4 m [6' to 8'] shark", "5 m  [16.5'] white shark",
       "2.5 m to 3 m [8.25' to 10']  white shark",
       '4.5 m [14\'9"] white shark',
       "2.3 m [7.5'] white shark, identified by M. Smale",
       'Tiger shark, 3 m ', "2.7 m [9'] white shark",
       'White shark, identified by tooth pattern',
       "4 m to 5 m [13' to 16.5']  white shark",
       ">3.4 m [11'] white shark", "Bronze whaler shark, 3 m [10'] ",
       "2 m [6.75'] white shark", "Tiger shark, 4 m [13'] ",
       "2.4 m to 3 m [8' to 10'] white shark", 'Sand shark?',
       "1.5 m to 2 m [5' to 6.75'] shark",
       'Zambezi shark (tooth fragments recovered)', '1.5 m copper shark',
       "1.8 m [6'] blacktip shark", "3.5 m [11.5']  white shark",
       '5.7 m white shark', '4.3 m shark', ">2.5 m [8.25'] white shark",
       "1.8 m to 2.1 m [6' to 7'] spinner or blacktip shark",
       "Lemon shark, 1.8 m to 2.4 m [6' to 8'], tooth fragment recovered",
       '1.6 m shark', "1.2 m [4'] dusky shark", '>1 m shark',
       ">2.4 m [8'] white shark", "Raggedtooth shark, 2 m [6.75'] ",
       'Bronze whaler shark, 3.5 m ',
       "2 m to 2.5 m [6.75'  to 8.25'] sixgill or sevengill shark",
       'Possibly a small hammerhead shark',
       '3 m to 3.6 m  [10\' to 11\'9"] white shark',
       '3.5 m white shark, tooth fragments recovered',
       'Tiger shark, 4 m ',
       'Shark involvement not confirmed; officials considered barracua',
       '4.5 m to 5 m white shark', "2.4 m [8'] white shark",
       "1.2 m to 1.5 m [4' to 5'] hammerhead shark",
       " 1.5 m [5'] dusky shark", 'Raggedtooth shark, 1 m ',
       'Raggedtooth shark, >1 m ', "Tiger shark, 5 m [16.5']",
       "6' blacktip shark",
       "Raggedtooth shark, 1.5 m [5'] (tooth fragment recovered)",
       "1.8 m [6'] Zambezi shark",
       'Believed to involve a 2.8 m [9\'3"] white shark',
       'Questionable incident; reported as shark attack but thought to involve a pinniped instead ',
       "2.4 m [8'] white shark, species identity confirmed by tooth fragment",
       "4.5 m to 5.5 m [14.7' to 18'] white shark",
       "2.4 m [8'] white shark, species identity confirmed by witnesses & tooth pattern in surfboard",
       'Mako shark (tooth fragments recovered)',
       "Possibly a  1.8 m [6'] Zambezi shark", '6 m  white shark',
       "Raggedtooth shark, 2.5 m [8.25'] ", "Tiger shark, 2.1 m [7']",
       "1.2 m to 1.5 m [4' to 5'] bull, sandbar or dusky shark",
       'C. maculpinnis or C. limbatus',
       'Juvenile dusky or blacktip shark',
       "1.8 m to 2.4 m [6' to 8'] hammerhead shark",
       'Tiger shark, 2.5 m ', "3.5 m [11.5'] shark",
       '2.8 m [9\'3"] white shark', '2 m [6\'9"] Zambesi shark',
       'Raggedtooth shark, 2 m [6\'9"] ', "White shark, 2.5 m [8.25']  ",
       "White shark, 2.3 m [7.5'], tooth fragment recovered",
       "White shark, 3.7 m [12'] ", 'Thought to involve a blacktip shark',
       "White shark, 5.5 m [18'] ", "White shark, 3 m [10'] k",
       "2.1 m [7'] lemon shark or bull shark",
       "White shark, 3 m to 4 m [10' to 13'] ", "Tiger shark, 6' ",
       'White shark, 4.5 m ', 'Juvenile dusky shark',
       "White shark, 2.4 m [8']", "White shark, 5.8 m [19'] ",
       'White shark, 5m to 6m', "White shark, 3 m [10'] ",
       "White shark, 5.5 m to 6 m [18' to 20'] ",
       'White shark, 4 m to 5 m ',
       "White shark, 5 m to 6 m [16.5 to 20'] ",
       "White shark, 5 m [16.5']", "2 m to 2.5 m [6.75'  to 8.25'] shark",
       "7' to 8' bull shark",
       "White shark, 4.4 m to 5 m [14.5' to 16.5'] ", 'Zambesi shark',
       "White shark, 2.5 m [8.25'] ", "White shark, 3 m [10']rk",
       "White shark, 5 m to 6 m [16.5' to 20']  ",
       "Grey nurse shark, 11'",
       "White shark, 3 m [10'], species identity confirmed by witnesses & tooth pattern in leg & board ",
       '1.8 to 2 m C. albimarginatus',
       'Raggedtooth shark, 2 m [6\'9"], 5-year-old, captive female ',
       "White shark, 4.3 m 4.9 m [14' to 16'] ",
       'White shark, identified by tooth fragments in surfboard',
       "White shark, 4.3 m [14'], (tooth fragment recovered)",
       "White shark, 4 m [13'] ", "2.7 m [9'] silky shark",
       'small blacktip shark', "5' blue shark",
       'Nurse shark, 106 cm, 28-lb, male ', 'Nurse shark, 1 m ',
       'Grey nurse shark', "3.7 m [12'] shark",
       "Bronze whaler shark, 2.1 m [7'], a tooth was embedded in the speargun ",
       "Mako shark, 1.9 m [6.5'] ", 'Spinner or blacktip sharks',
       "Local authorities speculated that the water was too cold for sharks, but a 2.1 m [7'], 200-lb pregnant sandbar shark was caught next day",
       "1.2 m [4'] hammerhead shark",
       "White shark, 2.5 m [8.25'], an immature female, previously injured",
       "1.5 m to 1.8 m [5' to 6'] Zambesi shark",
       '1.8 m to 2 m [6\' to 6\'9"] shark', 'Hammerhead shark',
       "Grey nurse shark, 2.4 m [8'] ", '300-kg [662-lb] shark',
       'Tiger shark, tooth fragment recovered', 'Raggedtooth shark ',
       "White shark, 2.4 m [8'] ", "Grey nurse shark, 1.8 m [6']",
       "1.8 to 2.4 m [6' to 8'] shark", "1.7 m [5.5'] shark",
       "White shark, 1.5 m [5'] k",
       "White shark, 3 m to 3.7 m [10' to 12'] ",
       'White shark (tooth fragment recovered)', "1.8 m [6']  shark",
       'Dusky shark, 1 m ', '300- to 400-lb Zambesi shark',
       ">1.2 m [4'] tiger shark",
       'Dooley believed his Injury was caused by stingray (Dasyatidae family)',

sharkdf.Species=sharkdf.Species.apply(lambda x : re.sub('[a-z ]*?[san]?[d]tiguer[a-z ]* ?\W?','Unknown', x))
sharkdf.Species=sharkdf.Species.apply(lambda x : re.sub('[a-z ]*?[san]?[d]tiguer[a-z ]* ?\W?','Unknown', x))
sharkdf.Species=sharkdf.Species.apply(lambda x : re.sub('[a-z ]*?[san]?[d]tiguer[a-z ]* ?\W?','Unknown', x))
sharkdf.Species=sharkdf.Species.apply(lambda x : re.sub('[a-z ]*?[san]?[d]tiguer[a-z ]* ?\W?','Unknown', x))
sharkdf.Species=sharkdf.Species.apply(lambda x : re.sub('[a-z ]*?[san]?[d]tiguer[a-z ]* ?\W?','Unknown', x))
sharkdf.Species=sharkdf.Species.apply(lambda x : re.sub('[a-z ]*?[san]?[d]tiguer[a-z ]* ?\W?','Unknown', x))
sharkdf.Species=sharkdf.Species.apply(lambda x : re.sub('[a-z ]*?[san]?[d]tiguer[a-z ]* ?\W?','Unknown', x))
sharkdf.Species=sharkdf.Species.apply(lambda x : re.sub('[a-z ]*?[san]?[d]tiguer[a-z ]* ?\W?','Unknown', x))
sharkdf.Species=sharkdf.Species.apply(lambda x : re.sub('[a-z ]*?[san]?[d]tiguer[a-z ]* ?\W?','Unknown', x))

In [1446]:
sharkdf.Sex = sharkdf.Sex.fillna('Unknown')

In [1447]:
sharkdf.Sex

0       F
8       M
13      M
18      M
21      M
       ..
5273    M
5311    M
5375    M
5484    M
5545    M
Name: Sex, Length: 1218, dtype: object

In [1448]:
sharkdf.Sex.unique()

array(['F', 'M', 'lli', 'Unknown'], dtype=object)

In [1449]:
def sexo(x):
    for i in x: 
        if i == 'M':
            return 'M'
        elif i == 'F':
            return 'F'
        else:
            return 'Unknown'

In [1450]:
sexlst = list(sharkdf['Sex'])
sexlst

['F',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'F',
 'M',
 'M',
 'M',
 'M',
 'F',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'F',
 'M',
 'M',
 'M',
 'F',
 'M',
 'M',
 'F',
 'F',
 'F',
 'M',
 'F',
 'M',
 'M',
 'M',
 'M',
 'M',
 'F',
 'M',
 'M',
 'M',
 'F',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'F',
 'M',
 'M',
 'F',
 'M',
 'M',
 'F',
 'M',
 'M',
 'F',
 'M',
 'M',
 'M',
 'F',
 'F',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'F',
 'M',
 'M',
 'F',
 'F',
 'M',
 'M',
 'F',
 'M',
 'M',
 'M',
 'M',
 'F',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'F',
 'M',
 'F',
 'F',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'F',
 'M',
 'M',
 'M',
 'M',
 'M',
 'F',
 'F',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'F',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'F',
 'M',
 'F',
 'M',
 'M',
 'F',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'F',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'F',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'F',
 'M',
 'M',
 'M',
 'M',
 'F',
 'F',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'F',
 'M',
 'M',
 'M',
 'M',
 'F',
 'M',
 'M',
 'F',
 'M',
 'M',
 'M',
 'M',
 'F',
 'M',
 'F',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'F',
 'M',
 'M',
 'F',
 'M',
 'F',
 'M',
 'F',
 'M',
 'M',
 'F',
 'F',
 'M',
 'M',
 'M',
 'M',
 'F',
 'M',
 'F',
 'M',
 'M',
 'M',
 'F',
 'M',
 'F',
 'F',
 'F',
 'M',
 'M',
 'M',
 'M',
 'F',
 'M',
 'M',
 'M',
 'F',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'F',
 'F',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'F',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'F',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'F',
 'M',
 'M',
 'M',
 'F',
 'F',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'F',
 'M',
 'M',
 'F',
 'F',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'F',
 'M',
 'M',
 'M',
 'F',
 'F',
 'F',
 'M',
 'F',
 'F',
 'M',
 'F',
 'M',
 'F',
 'M',
 'F',
 'M',
 'M',
 'M',
 'M',
 'F',
 'F',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'F',
 'M',
 'F',
 'M',
 'M',
 'M',
 'F',
 'M',
 'M',
 'M',
 'F',
 'M',
 'M',
 'F',
 'F',
 'M',
 'F',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'F',
 'M',
 'M',
 'F',
 'F',
 'M',
 'M',
 'M',
 'M',
 'M',
 'F',
 'M',
 'F',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'F',
 'lli',
 'M',
 'M',
 'M',
 'M',
 'F',
 'M',
 'M',
 'M',
 'F',
 'F',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'F',
 'M',
 'F',
 'M',
 'M',
 'F',
 'M',
 'M',
 'M',
 'F',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'F',
 'F',
 'M',
 'M',
 'F',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'F',
 'F',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'F',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'F',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'F',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'Unknown',
 'F',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'F',
 'F',
 'F',
 'F',
 'F',
 'M',
 'M',
 'M',
 'M',
 'F',
 'M',
 'M',
 'M',
 'F',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'F',
 'M',
 'F',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'F',
 'F',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'F',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'F',
 'M',
 'M',
 'F',
 'M',
 'M',
 'F',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'F',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'F',
 'F',
 'M',
 'F',
 'M',
 'M',
 'M',
 'M',
 'F',
 'M',
 'M',
 'M',
 'M',
 'M',
 'F',
 'F',
 'M',
 'M',
 'M',
 'F',
 'M',
 'M',
 'F',
 'M',
 'F',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'F',
 'M',
 'M',
 'F',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'F',
 'M',
 'M',
 'M',
 'M',
 'M',
 'F',
 'F',
 'M',
 'M',
 'M',
 'F',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'F',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'F',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'F',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'F',
 'F',
 'M',
 'M',
 'M',
 'M',
 'M',
 'F',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'F',
 'M',
 'F',
 'M',
 'M',
 'M',
 'M',
 'M',
 'F',
 'F',
 'M',
 'M',
 'M',
 'F',
 'M',
 'M',
 'F',
 'M',
 'M',
 'M',
 'M',
 'F',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'F',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'F',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'F',
 'M',
 'F',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'F',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 'M',
 ...]

In [1451]:
sharkdf.Sex = sexo(sexlst)

In [1452]:
sharkdf.Sex.unique()

array(['F'], dtype=object)

In [1453]:
sharkdf.Sex

0       F
8       F
13      F
18      F
21      F
       ..
5273    F
5311    F
5375    F
5484    F
5545    F
Name: Sex, Length: 1218, dtype: object

In [84]:
sharkdf.shape

(1560, 24)